// Country and state data constants
export const COUNTRIES = [
  // Most relevant countries first
  { id: 'US', code: '+1', flag: '🇺🇸', name: 'United States' },
  { id: 'CA', code: '+1', flag: '🇨🇦', name: 'Canada' },
  
  // Then alphabetical by country name
  { id: 'AF', code: '+93', flag: '🇦🇫', name: 'Afghanistan' },
  { id: 'AL', code: '+355', flag: '🇦🇱', name: 'Albania' },
  { id: 'DZ', code: '+213', flag: '🇩🇿', name: 'Algeria' },
  { id: 'AD', code: '+376', flag: '🇦🇩', name: 'Andorra' },
  { id: 'AO', code: '+244', flag: '🇦🇴', name: 'Angola' },
  { id: 'AI', code: '+1264', flag: '🇦🇮', name: 'Anguilla' },
  { id: 'AQ', code: '+672', flag: '🇦🇶', name: 'Antarctica' },
  { id: 'AG', code: '+1268', flag: '🇦🇬', name: 'Antigua and Barbuda' },
  { id: 'AR', code: '+54', flag: '🇦🇷', name: 'Argentina' },
  { id: 'AM', code: '+374', flag: '🇦🇲', name: 'Armenia' },
  { id: 'AW', code: '+297', flag: '🇦🇼', name: 'Aruba' },
  { id: 'AU', code: '+61', flag: '🇦🇺', name: 'Australia' },
  { id: 'AT', code: '+43', flag: '🇦🇹', name: 'Austria' },
  { id: 'AZ', code: '+994', flag: '🇦🇿', name: 'Azerbaijan' },
  { id: 'BS', code: '+1242', flag: '🇧🇸', name: 'Bahamas' },
  { id: 'BH', code: '+973', flag: '🇧🇭', name: 'Bahrain' },
  { id: 'BD', code: '+880', flag: '🇧🇩', name: 'Bangladesh' },
  { id: 'BB', code: '+1246', flag: '🇧🇧', name: 'Barbados' },
  { id: 'BY', code: '+375', flag: '🇧🇾', name: 'Belarus' },
  { id: 'BE', code: '+32', flag: '🇧🇪', name: 'Belgium' },
  { id: 'BZ', code: '+501', flag: '🇧🇿', name: 'Belize' },
  { id: 'BJ', code: '+229', flag: '🇧🇯', name: 'Benin' },
  { id: 'BM', code: '+1441', flag: '🇧🇲', name: 'Bermuda' },
  { id: 'BT', code: '+975', flag: '🇧🇹', name: 'Bhutan' },
  { id: 'BO', code: '+591', flag: '🇧🇴', name: 'Bolivia' },
  { id: 'BA', code: '+387', flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
  { id: 'BW', code: '+267', flag: '🇧🇼', name: 'Botswana' },
  { id: 'BR', code: '+55', flag: '🇧🇷', name: 'Brazil' },
  { id: 'BN', code: '+673', flag: '🇧🇳', name: 'Brunei' },
  { id: 'BG', code: '+359', flag: '🇧🇬', name: 'Bulgaria' },
  { id: 'BF', code: '+226', flag: '🇧🇫', name: 'Burkina Faso' },
  { id: 'BI', code: '+257', flag: '🇧🇮', name: 'Burundi' },
  { id: 'KH', code: '+855', flag: '🇰🇭', name: 'Cambodia' },
  { id: 'CM', code: '+237', flag: '🇨🇲', name: 'Cameroon' },
  { id: 'CV', code: '+238', flag: '🇨🇻', name: 'Cape Verde' },
  { id: 'KY', code: '+1345', flag: '🇰🇾', name: 'Cayman Islands' },
  { id: 'CF', code: '+236', flag: '🇨🇫', name: 'Central African Republic' },
  { id: 'TD', code: '+235', flag: '🇹🇩', name: 'Chad' },
  { id: 'CL', code: '+56', flag: '🇨🇱', name: 'Chile' },
  { id: 'CN', code: '+86', flag: '🇨🇳', name: 'China' },
  { id: 'CO', code: '+57', flag: '🇨🇴', name: 'Colombia' },
  { id: 'KM', code: '+269', flag: '🇰🇲', name: 'Comoros' },
  { id: 'CG', code: '+242', flag: '🇨🇬', name: 'Republic of the Congo' },
  { id: 'CD', code: '+243', flag: '🇨🇩', name: 'Democratic Republic of the Congo' },
  { id: 'CR', code: '+506', flag: '🇨🇷', name: 'Costa Rica' },
  { id: 'HR', code: '+385', flag: '🇭🇷', name: 'Croatia' },
  { id: 'CU', code: '+53', flag: '🇨🇺', name: 'Cuba' },
  { id: 'CY', code: '+357', flag: '🇨🇾', name: 'Cyprus' },
  { id: 'CZ', code: '+420', flag: '🇨🇿', name: 'Czech Republic' },
  { id: 'DK', code: '+45', flag: '🇩🇰', name: 'Denmark' },
  { id: 'DJ', code: '+253', flag: '🇩🇯', name: 'Djibouti' },
  { id: 'DM', code: '+1767', flag: '🇩🇲', name: 'Dominica' },
  { id: 'DO', code: '+1809', flag: '🇩🇴', name: 'Dominican Republic' },
  { id: 'EC', code: '+593', flag: '🇪🇨', name: 'Ecuador' },
  { id: 'EG', code: '+20', flag: '🇪🇬', name: 'Egypt' },
  { id: 'SV', code: '+503', flag: '🇸🇻', name: 'El Salvador' },
  { id: 'GQ', code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea' },
  { id: 'ER', code: '+291', flag: '🇪🇷', name: 'Eritrea' },
  { id: 'EE', code: '+372', flag: '🇪🇪', name: 'Estonia' },
  { id: 'ET', code: '+251', flag: '🇪🇹', name: 'Ethiopia' },
  { id: 'FO', code: '+298', flag: '🇫🇴', name: 'Faroe Islands' },
  { id: 'FJ', code: '+679', flag: '🇫🇯', name: 'Fiji' },
  { id: 'FI', code: '+358', flag: '🇫🇮', name: 'Finland' },
  { id: 'FR', code: '+33', flag: '🇫🇷', name: 'France' },
  { id: 'GF', code: '+594', flag: '🇬🇫', name: 'French Guiana' },
  { id: 'PF', code: '+689', flag: '🇵🇫', name: 'French Polynesia' },
  { id: 'GA', code: '+241', flag: '🇬🇦', name: 'Gabon' },
  { id: 'GM', code: '+220', flag: '🇬🇲', name: 'Gambia' },
  { id: 'GE', code: '+995', flag: '🇬🇪', name: 'Georgia' },
  { id: 'DE', code: '+49', flag: '🇩🇪', name: 'Germany' },
  { id: 'GH', code: '+233', flag: '🇬🇭', name: 'Ghana' },
  { id: 'GI', code: '+350', flag: '🇬🇮', name: 'Gibraltar' },
  { id: 'GR', code: '+30', flag: '🇬🇷', name: 'Greece' },
  { id: 'GL', code: '+299', flag: '🇬🇱', name: 'Greenland' },
  { id: 'GD', code: '+1473', flag: '🇬🇩', name: 'Grenada' },
  { id: 'GP', code: '+590', flag: '🇬🇵', name: 'Guadeloupe' },
  { id: 'GU', code: '+1671', flag: '🇬🇺', name: 'Guam' },
  { id: 'GT', code: '+502', flag: '🇬🇹', name: 'Guatemala' },
  { id: 'GN', code: '+224', flag: '🇬🇳', name: 'Guinea' },
  { id: 'GW', code: '+245', flag: '🇬🇼', name: 'Guinea-Bissau' },
  { id: 'GY', code: '+592', flag: '🇬🇾', name: 'Guyana' },
  { id: 'HT', code: '+509', flag: '🇭🇹', name: 'Haiti' },
  { id: 'HN', code: '+504', flag: '🇭🇳', name: 'Honduras' },
  { id: 'HK', code: '+852', flag: '🇭🇰', name: 'Hong Kong' },
  { id: 'HU', code: '+36', flag: '🇭🇺', name: 'Hungary' },
  { id: 'IS', code: '+354', flag: '🇮🇸', name: 'Iceland' },
  { id: 'IN', code: '+91', flag: '🇮🇳', name: 'India' },
  { id: 'ID', code: '+62', flag: '🇮🇩', name: 'Indonesia' },
  { id: 'IQ', code: '+964', flag: '🇮🇶', name: 'Iraq' },
  { id: 'IE', code: '+353', flag: '🇮🇪', name: 'Ireland' },
  { id: 'IL', code: '+972', flag: '🇮🇱', name: 'Israel' },
  { id: 'IT', code: '+39', flag: '🇮🇹', name: 'Italy' },
  { id: 'JM', code: '+1876', flag: '🇯🇲', name: 'Jamaica' },
  { id: 'JP', code: '+81', flag: '🇯🇵', name: 'Japan' },
  { id: 'JO', code: '+962', flag: '🇯🇴', name: 'Jordan' },
  { id: 'KZ', code: '+7', flag: '🇰🇿', name: 'Kazakhstan' },
  { id: 'KE', code: '+254', flag: '🇰🇪', name: 'Kenya' },
  { id: 'KR', code: '+82', flag: '🇰🇷', name: 'South Korea' },
  { id: 'KW', code: '+965', flag: '🇰🇼', name: 'Kuwait' },
  { id: 'KG', code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan' },
  { id: 'LA', code: '+856', flag: '🇱🇦', name: 'Laos' },
  { id: 'LV', code: '+371', flag: '🇱🇻', name: 'Latvia' },
  { id: 'LB', code: '+961', flag: '🇱🇧', name: 'Lebanon' },
  { id: 'LI', code: '+423', flag: '🇱🇮', name: 'Liechtenstein' },
  { id: 'LT', code: '+370', flag: '🇱🇹', name: 'Lithuania' },
  { id: 'LU', code: '+352', flag: '🇱🇺', name: 'Luxembourg' },
  { id: 'MO', code: '+853', flag: '🇲🇴', name: 'Macau' },
  { id: 'MK', code: '+389', flag: '🇲🇰', name: 'North Macedonia' },
  { id: 'MG', code: '+261', flag: '🇲🇬', name: 'Madagascar' },
  { id: 'MW', code: '+265', flag: '🇲🇼', name: 'Malawi' },
  { id: 'MY', code: '+60', flag: '🇲🇾', name: 'Malaysia' },
  { id: 'MV', code: '+960', flag: '🇲🇻', name: 'Maldives' },
  { id: 'ML', code: '+223', flag: '🇲🇱', name: 'Mali' },
  { id: 'MT', code: '+356', flag: '🇲🇹', name: 'Malta' },
  { id: 'MQ', code: '+596', flag: '🇲🇶', name: 'Martinique' },
  { id: 'MR', code: '+222', flag: '🇲🇷', name: 'Mauritania' },
  { id: 'MU', code: '+230', flag: '🇲🇺', name: 'Mauritius' },
  { id: 'MX', code: '+52', flag: '🇲🇽', name: 'Mexico' },
  { id: 'MD', code: '+373', flag: '🇲🇩', name: 'Moldova' },
  { id: 'MC', code: '+377', flag: '🇲🇨', name: 'Monaco' },
  { id: 'MN', code: '+976', flag: '🇲🇳', name: 'Mongolia' },
  { id: 'ME', code: '+382', flag: '🇲🇪', name: 'Montenegro' },
  { id: 'MS', code: '+1664', flag: '🇲🇸', name: 'Montserrat' },
  { id: 'MA', code: '+212', flag: '🇲🇦', name: 'Morocco' },
  { id: 'MZ', code: '+258', flag: '🇲🇿', name: 'Mozambique' },
  { id: 'MM', code: '+95', flag: '🇲🇲', name: 'Myanmar' },
  { id: 'NA', code: '+264', flag: '🇳🇦', name: 'Namibia' },
  { id: 'NP', code: '+977', flag: '🇳🇵', name: 'Nepal' },
  { id: 'NL', code: '+31', flag: '🇳🇱', name: 'Netherlands' },
  { id: 'NC', code: '+687', flag: '🇳🇨', name: 'New Caledonia' },
  { id: 'NZ', code: '+64', flag: '🇳🇿', name: 'New Zealand' },
  { id: 'NI', code: '+505', flag: '🇳🇮', name: 'Nicaragua' },
  { id: 'NE', code: '+227', flag: '🇳🇪', name: 'Niger' },
  { id: 'NG', code: '+234', flag: '🇳🇬', name: 'Nigeria' },
  { id: 'NO', code: '+47', flag: '🇳🇴', name: 'Norway' },
  { id: 'OM', code: '+968', flag: '🇴🇲', name: 'Oman' },
  { id: 'PK', code: '+92', flag: '🇵🇰', name: 'Pakistan' },
  { id: 'PA', code: '+507', flag: '🇵🇦', name: 'Panama' },
  { id: 'PG', code: '+675', flag: '🇵🇬', name: 'Papua New Guinea' },
  { id: 'PY', code: '+595', flag: '🇵🇾', name: 'Paraguay' },
  { id: 'PE', code: '+51', flag: '🇵🇪', name: 'Peru' },
  { id: 'PH', code: '+63', flag: '🇵🇭', name: 'Philippines' },
  { id: 'PL', code: '+48', flag: '🇵🇱', name: 'Poland' },
  { id: 'PT', code: '+351', flag: '🇵🇹', name: 'Portugal' },
  { id: 'PR', code: '+1787', flag: '🇵🇷', name: 'Puerto Rico' },
  { id: 'QA', code: '+974', flag: '🇶🇦', name: 'Qatar' },
  { id: 'RO', code: '+40', flag: '🇷🇴', name: 'Romania' },
  { id: 'RW', code: '+250', flag: '🇷🇼', name: 'Rwanda' },
  { id: 'SA', code: '+966', flag: '🇸🇦', name: 'Saudi Arabia' },
  { id: 'SN', code: '+221', flag: '🇸🇳', name: 'Senegal' },
  { id: 'RS', code: '+381', flag: '🇷🇸', name: 'Serbia' },
  { id: 'SG', code: '+65', flag: '🇸🇬', name: 'Singapore' },
  { id: 'SK', code: '+421', flag: '🇸🇰', name: 'Slovakia' },
  { id: 'SI', code: '+386', flag: '🇸🇮', name: 'Slovenia' },
  { id: 'ZA', code: '+27', flag: '🇿🇦', name: 'South Africa' },
  { id: 'ES', code: '+34', flag: '🇪🇸', name: 'Spain' },
  { id: 'LK', code: '+94', flag: '🇱🇰', name: 'Sri Lanka' },
  { id: 'SD', code: '+249', flag: '🇸🇩', name: 'Sudan' },
  { id: 'SR', code: '+597', flag: '🇸🇷', name: 'Suriname' },
  { id: 'SE', code: '+46', flag: '🇸🇪', name: 'Sweden' },
  { id: 'CH', code: '+41', flag: '🇨🇭', name: 'Switzerland' },
  { id: 'SY', code: '+963', flag: '🇸🇾', name: 'Syria' },
  { id: 'TW', code: '+886', flag: '🇹🇼', name: 'Taiwan' },
  { id: 'TJ', code: '+992', flag: '🇹🇯', name: 'Tajikistan' },
  { id: 'TZ', code: '+255', flag: '🇹🇿', name: 'Tanzania' },
  { id: 'TH', code: '+66', flag: '🇹🇭', name: 'Thailand' },
  { id: 'TL', code: '+670', flag: '🇹🇱', name: 'Timor-Leste' },
  { id: 'TG', code: '+228', flag: '🇹🇬', name: 'Togo' },
  { id: 'TN', code: '+216', flag: '🇹🇳', name: 'Tunisia' },
  { id: 'TR', code: '+90', flag: '🇹🇷', name: 'Turkey' },
  { id: 'TM', code: '+993', flag: '🇹🇲', name: 'Turkmenistan' },
  { id: 'TC', code: '+1649', flag: '🇹🇨', name: 'Turks and Caicos Islands' },
  { id: 'UG', code: '+256', flag: '🇺🇬', name: 'Uganda' },
  { id: 'UA', code: '+380', flag: '🇺🇦', name: 'Ukraine' },
  { id: 'AE', code: '+971', flag: '🇦🇪', name: 'United Arab Emirates' },
  { id: 'GB', code: '+44', flag: '🇬🇧', name: 'United Kingdom' },
  { id: 'UY', code: '+598', flag: '🇺🇾', name: 'Uruguay' },
  { id: 'UZ', code: '+998', flag: '🇺🇿', name: 'Uzbekistan' },
  { id: 'VE', code: '+58', flag: '🇻🇪', name: 'Venezuela' },
  { id: 'VN', code: '+84', flag: '🇻🇳', name: 'Vietnam' },
  { id: 'YE', code: '+967', flag: '🇾🇪', name: 'Yemen' },
  { id: 'ZM', code: '+260', flag: '🇿🇲', name: 'Zambia' },
  { id: 'ZW', code: '+263', flag: '🇿🇼', name: 'Zimbabwe' }
];

export const US_STATES = [
  { value: '', label: '- Select Province/State -' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  // Canadian Provinces
  { value: 'AB', label: 'Alberta' },
  { value: 'BC', label: 'British Columbia' },
  { value: 'MB', label: 'Manitoba' },
  { value: 'NB', label: 'New Brunswick' },
  { value: 'NL', label: 'Newfoundland and Labrador' },
  { value: 'NS', label: 'Nova Scotia' },
  { value: 'NT', label: 'Northwest Territories' },
  { value: 'NU', label: 'Nunavut' },
  { value: 'ON', label: 'Ontario' },
  { value: 'PE', label: 'Prince Edward Island' },
  { value: 'QC', label: 'Quebec' },
  { value: 'SK', label: 'Saskatchewan' },
  { value: 'YT', label: 'Yukon' }
]; 