blank_issues_enabled: false
contact_links:
  - name: 💬 Quick Questions
    url: https://github.com/yourusername/yourrepo/discussions
    about: For quick dev questions and discussions
  - name: 📋 Project Board
    url: https://github.com/yourusername/yourrepo/projects
    about: View current sprint and project status
